const UART_SERVICE="6e400001-b5a3-f393-e0a9-e50e24dcca9e",UART_WRITE="6e400003-b5a3-f393-e0a9-e50e24dcca9e",UART_NOTIFY="6e400002-b5a3-f393-e0a9-e50e24dcca9e";
let writer=null,driveTimer=null;
const $=id=>document.getElementById(id),status=$("status"),dot=$("dot"),buttons=[...document.querySelectorAll("[data-command]")];
function setStatus(text){status.textContent=text}function clearDrive(){clearInterval(driveTimer);driveTimer=null}async function send(command){if(!writer)throw new Error("尚未連接 micro:bit");const data=new TextEncoder().encode(command+"\n");return writer.properties.writeWithoutResponse?writer.writeValueWithoutResponse(data):writer.writeValueWithResponse(data)}
function stop(message){clearDrive();if(writer)send("K").catch(()=>{});if(message)setStatus(message)}
function begin(command,label){clearDrive();send(command).catch(()=>stop("傳送失敗，請重新連線"));driveTimer=setInterval(()=>send(command).catch(()=>stop("傳送失敗，小車已停止")),150);setStatus("行駛中："+label+"（放開即停止）")}
function enableControls(enabled){buttons.forEach(button=>button.disabled=!enabled)}
$("connect").addEventListener("click",async()=>{if(!navigator.bluetooth){setStatus("請使用 Chrome 或 Edge，並確認電腦藍牙已開啟");return}try{setStatus("請在清單中選擇 micro:bit…");const device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[UART_SERVICE]});device.addEventListener("gattserverdisconnected",()=>{stop();writer=null;enableControls(false);dot.classList.remove("online");setStatus("藍牙已中斷，小車已停止")});const server=await device.gatt.connect(),service=await server.getPrimaryService(UART_SERVICE);writer=await service.getCharacteristic(UART_WRITE);const notifier=await service.getCharacteristic(UART_NOTIFY);notifier.addEventListener("characteristicvaluechanged",event=>{const reply=new TextDecoder().decode(event.target.value.buffer).trim();if(reply.startsWith("ACK:"))setStatus("已連線 · micro:bit 已收到 "+reply.slice(4))});await notifier.startNotifications();dot.classList.add("online");enableControls(true);setStatus("已連線："+(device.name||"micro:bit"))}catch(error){setStatus(error.name==="NotFoundError"?"找不到或尚未選擇裝置：確認 micro:bit 已上電後再試":"連線失敗："+(error.message||"請重開 micro:bit 後再試"))}});
buttons.forEach(button=>{const start=event=>{event.preventDefault();begin(button.dataset.command,button.dataset.label)};button.addEventListener("pointerdown",start);["pointerup","pointerleave","pointercancel"].forEach(name=>button.addEventListener(name,()=>stop("已停止")))});document.addEventListener("pointerup",()=>{if(driveTimer)stop("已停止")});
const keys={q:"Q",w:"W",e:"E",a:"A",s:"S",d:"D",z:"Z",x:"X",c:"C",j:"J"};window.addEventListener("keydown",event=>{const command=keys[event.key.toLowerCase()];if(command&&!event.repeat){event.preventDefault();const button=buttons.find(item=>item.dataset.command===command);if(button&&!button.disabled)begin(command,button.dataset.label)}if(event.key===" "){event.preventDefault();stop("已立即停止")}});window.addEventListener("keyup",event=>{if(keys[event.key.toLowerCase()])stop("已停止")});$("stop").addEventListener("click",()=>stop("已立即停止"));
