const UART_SERVICE="6e400001-b5a3-f393-e0a9-e50e24dcca9e",UART_WRITE="6e400003-b5a3-f393-e0a9-e50e24dcca9e",UART_NOTIFY="6e400002-b5a3-f393-e0a9-e50e24dcca9e",REPEAT=150,MAX_SECONDS=5;
let writer=null,recognition=null,repeatTimer=null,stopTimer=null;
const $=id=>document.getElementById(id),status=$("status"),dot=$("dot"),listen=$("listen"),heard=$("heard"),movement=$("movement"),driveButtons=[...document.querySelectorAll("[data-command]")];
const setStatus=text=>status.textContent=text;
function clearTimers(){clearInterval(repeatTimer);clearTimeout(stopTimer);repeatTimer=stopTimer=null}
async function send(command){if(!writer)throw new Error("尚未連接 micro:bit");const data=new TextEncoder().encode(command+"\n");return writer.properties.writeWithoutResponse?writer.writeValueWithoutResponse(data):writer.writeValueWithResponse(data)}
function setMoving(text){movement.textContent=text?"🚗 "+text:"● 安全待命中";movement.classList.toggle("moving",!!text)}
function stopCar(message){clearTimers();setMoving("");if(writer)send("K").catch(()=>{});if(message)heard.textContent=message}
function numberOf(value){if(/^\d+(\.\d+)?$/.test(value))return Number(value);if(value==="半")return .5;const map={零:0,〇:0,一:1,二:2,兩:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9};let total=0,current=0;for(const char of value){if(char in map)current=map[char];else if(char==="十"){total+=(current||1)*10;current=0}else return null}return total+current}
function driveTime(text){const match=text.match(/([0-9]+(?:\.[0-9]+)?|[零〇一二兩三四五六七八九十半]+)\s*(?:秒鐘?|秒)/),seconds=match?numberOf(match[1]):null;return seconds===null?[1,"1 秒"]:[seconds,seconds+" 秒"]}
function timedDrive(command,label,requested,description){clearTimers();const seconds=Math.min(MAX_SECONDS,Math.max(.2,requested));setMoving(label+"中 · "+seconds.toFixed(Number.isInteger(seconds)?0:1)+" 秒");heard.textContent="執行："+label+" "+description+(requested>MAX_SECONDS?"（安全限制為 5 秒）":"");send(command).catch(()=>setStatus("傳送失敗，請重新連線"));repeatTimer=setInterval(()=>send(command).catch(()=>stopCar("傳送失敗，小車已停止")),REPEAT);stopTimer=setTimeout(()=>stopCar("完成："+label+" "+description),seconds*1000)}
function executeSpeech(spoken){const text=spoken.replace(/[，。！？,.!?\s]/g,"");heard.textContent="聽到：「"+spoken.trim()+"」";if(["停止","停車","煞車","停下來"].some(word=>text.includes(word)))return stopCar("已停止");const directions=[[["右上斜","右上","右前斜"],"E","右上斜"],[["右下斜","右下","右後斜"],"C","右下斜"],[["左上斜","左上","左前斜"],"Q","左上斜"],[["左下斜","左下","左後斜"],"Z","左下斜"],[["向左平移","左平移","往左平移"],"A","向左平移"],[["向右平移","右平移","往右平移"],"D","向右平移"],[["左轉","左旋轉"],"S","左轉"],[["右轉","右旋轉"],"J","右轉"],[["前進","往前","向前"],"W","前進"],[["後退","倒退","往後","向後"],"X","後退"]],direction=directions.find(([words])=>words.some(word=>text.includes(word)));if(direction){const [seconds,description]=driveTime(text);return timedDrive(direction[1],direction[2],seconds,description)}heard.textContent="無法辨識「"+spoken.trim()+"」，請參考下方說法再試一次"}
function setControls(enabled){listen.disabled=!enabled;driveButtons.forEach(button=>button.disabled=!enabled)}
$("connect").addEventListener("click",async()=>{if(!navigator.bluetooth){setStatus("請使用最新版 Chrome 或 Edge，並確認電腦藍牙已開啟");return}try{setStatus("請在清單中選擇 micro:bit…");const device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[UART_SERVICE]});device.addEventListener("gattserverdisconnected",()=>{clearTimers();writer=null;setControls(false);dot.classList.remove("online");setMoving("");setStatus("藍牙已中斷，小車已自動停止")});const server=await device.gatt.connect(),service=await server.getPrimaryService(UART_SERVICE);writer=await service.getCharacteristic(UART_WRITE);const notifier=await service.getCharacteristic(UART_NOTIFY);notifier.addEventListener("characteristicvaluechanged",event=>{const reply=new TextDecoder().decode(event.target.value.buffer).trim();if(reply.startsWith("ACK:"))setStatus("已連線 · micro:bit 已收到 "+reply.slice(4))});await notifier.startNotifications();dot.classList.add("online");setControls(true);setStatus("已連線："+(device.name||"micro:bit"));heard.textContent="按一下麥克風，或按下方方向按鈕"}catch(error){setStatus(error.name==="NotFoundError"?"找不到或尚未選擇裝置：確認 micro:bit 已上電並執行藍牙 UART 程式後再試":error.name==="NotSupportedError"?"這個裝置沒有 micro:bit 藍牙 UART 服務，請改選 micro:bit":"連線失敗："+(error.message||"請重開 micro:bit 後再試"))}});
driveButtons.forEach(button=>button.addEventListener("click",()=>timedDrive(button.dataset.command,button.dataset.label,1,"1 秒")));
$("listen").addEventListener("click",()=>{const Ctor=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Ctor){heard.textContent="此瀏覽器不支援語音辨識，請改用最新版 Chrome 或 Edge";return}recognition?.abort();recognition=new Ctor();recognition.lang="zh-TW";recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onresult=event=>{const result=event.results[event.resultIndex];if(result?.isFinal)executeSpeech(result[0].transcript)};recognition.onerror=event=>heard.textContent=event.error==="not-allowed"?"請允許瀏覽器使用麥克風後再試":"沒有聽清楚，請靠近麥克風再說一次";recognition.onend=()=>{listen.disabled=false;listen.classList.remove("listening");listen.querySelector("span").textContent="按一下說話"};listen.disabled=true;listen.classList.add("listening");listen.querySelector("span").textContent="正在聆聽…";heard.textContent="正在聽…例如說「右上斜」";recognition.start()});
$("stop").addEventListener("click",()=>stopCar("已立即停止"));
