const UART_SERVICE="6e400001-b5a3-f393-e0a9-e50e24dcca9e";
const UART_WRITE="6e400003-b5a3-f393-e0a9-e50e24dcca9e";
const UART_NOTIFY="6e400002-b5a3-f393-e0a9-e50e24dcca9e";
const CONTROLLER_BEACON_SERVICE="0000feaa-0000-1000-8000-00805f9b34fb";
const DRIVE_REPEAT_MS=150,MAX_DRIVE_SECONDS=5;
let writer=null,recognition=null,repeatTimer=null,stopTimer=null;
const $=id=>document.getElementById(id),status=$("status"),dot=$("dot"),listen=$("listen"),heard=$("heard"),movement=$("movement");
const setStatus=text=>status.textContent=text;
function clearTimers(){clearInterval(repeatTimer);clearTimeout(stopTimer);repeatTimer=stopTimer=null}
async function send(command){if(!writer)throw new Error("尚未連接 micro:bit");const data=new TextEncoder().encode(command+"\n");if(writer.properties.writeWithoutResponse)await writer.writeValueWithoutResponse(data);else await writer.writeValueWithResponse(data)}
function setMoving(text){movement.textContent=text?"🚗 "+text:"● 安全待命中";movement.classList.toggle("moving",!!text)}
function stopCar(message){clearTimers();setMoving("");if(writer)send("K").catch(()=>{});if(message)heard.textContent=message}
function runAction(command,label){clearTimers();setMoving("");send("K").then(()=>send(command)).then(()=>heard.textContent="執行："+label).catch(()=>setStatus("指令傳送失敗，請重新連線"))}
function parseNumber(value){value=value.replace(/\s/g,"");if(/^\d+(\.\d+)?$/.test(value))return Number(value);if(value==="半")return .5;const map={零:0,〇:0,一:1,二:2,兩:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9};if(value.includes("點")){const [a,b=""]=value.split("點"),n=parseNumber(a||"零"),d=[...b].map(x=>map[x]);return n===null||d.includes(undefined)?null:Number(n+"."+d.join(""))}let total=0,current=0;for(const c of value){if(c in map)current=map[c];else if(c==="十"){total+=(current||1)*10;current=0}else if(c==="百"){total+=(current||1)*100;current=0}else return null}return total+current}
function amount(text,units){const m=text.match(new RegExp("([0-9]+(?:\\.[0-9]+)?|[零〇一二兩三四五六七八九十百點半]+)\\s*(?:"+units+")"));return m?parseNumber(m[1]):null}
function driveTime(text){let n=amount(text,"毫秒");if(n!==null)return[n/1000,n+" 毫秒"];n=amount(text,"秒鐘?|秒");if(n!==null)return[n,n+" 秒"];const speed=Math.max(1,Number($("speed").value)||25);n=amount(text,"公分|厘米");if(n!==null)return[n/speed,"約 "+n+" 公分"];n=amount(text,"公尺|米");if(n!==null)return[n*100/speed,"約 "+n+" 公尺"];return[1,"1 秒"]}
function timedDrive(command,label,requested,description){clearTimers();const seconds=Math.min(MAX_DRIVE_SECONDS,Math.max(.2,requested));setMoving(label+"中 · "+seconds.toFixed(Number.isInteger(seconds)?0:1)+" 秒");heard.textContent="執行："+label+" "+description+(requested>MAX_DRIVE_SECONDS?"（安全限制為 5 秒）":"");send(command).catch(()=>setStatus("傳送失敗，請重新連線"));repeatTimer=setInterval(()=>send(command).catch(()=>stopCar("傳送失敗，小車已停止")),DRIVE_REPEAT_MS);stopTimer=setTimeout(()=>stopCar("完成："+label+" "+description),seconds*1000)}
function executeSpeech(spoken){const text=spoken.replace(/[，。！？,.!?\s]/g,"");heard.textContent="聽到：「"+spoken.trim()+"」";if(["停止","停車","煞車","停下來"].some(w=>text.includes(w)))return stopCar("已停止");if(["夾子打開","夾爪打開","打開夾子","打開夾爪","放開"].some(w=>text.includes(w)))return runAction("O","夾子打開");if(["夾住","夾緊","夾起來","合起來","抓住"].some(w=>text.includes(w)))return runAction("C","夾子夾住");if(["手臂上升","手臂升起","升起手臂","手臂往上"].some(w=>text.includes(w)))return runAction("U","手臂上升");if(["手臂下降","手臂放下","放下手臂","手臂往下"].some(w=>text.includes(w)))return runAction("D","手臂下降");const dirs=[[ ["前進","往前","向前"],"F","前進"],[["後退","倒退","往後","向後"],"B","後退"],[["左轉","向左","往左"],"L","左轉"],[["右轉","向右","往右"],"R","右轉"]];const dir=dirs.find(([words])=>words.some(w=>text.includes(w)));if(dir){const [seconds,description]=driveTime(text);return timedDrive(dir[1],dir[2],seconds,description)}heard.textContent="無法辨識「"+spoken.trim()+"」，請參考下方說法再試一次"}
$("connect").addEventListener("click",async()=>{if(!navigator.bluetooth){setStatus("請使用最新版 Chrome 或 Edge，並確認藍牙已開啟");return}try{setStatus("請選擇你的 micro:bit…");const device=await navigator.bluetooth.requestDevice({filters:[{services:[CONTROLLER_BEACON_SERVICE]}],optionalServices:[UART_SERVICE]});device.addEventListener("gattserverdisconnected",()=>{clearTimers();writer=null;listen.disabled=true;dot.classList.remove("online");setMoving("");setStatus("藍牙已中斷，小車已自動停止")});const server=await device.gatt.connect(),service=await server.getPrimaryService(UART_SERVICE);writer=await service.getCharacteristic(UART_WRITE);const notifier=await service.getCharacteristic(UART_NOTIFY);notifier.addEventListener("characteristicvaluechanged",e=>{const reply=new TextDecoder().decode(e.target.value.buffer).trim();if(reply.startsWith("ACK:"))setStatus("已連線 · micro:bit 已收到 "+reply.slice(4))});await notifier.startNotifications();dot.classList.add("online");listen.disabled=false;setStatus("已連線："+(device.name||"micro:bit"));heard.textContent="按一下麥克風，再說出完整指令"}catch(error){setStatus(error.name==="NotFoundError"?"尚未選擇裝置":"連線失敗："+(error.message||"請重開 micro:bit 後再試"))}});
$("listen").addEventListener("click",()=>{const Ctor=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Ctor){heard.textContent="此瀏覽器不支援語音辨識，請改用最新版 Chrome 或 Edge";return}recognition?.abort();recognition=new Ctor();recognition.lang="zh-TW";recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onresult=e=>{const result=e.results[e.resultIndex];if(result?.isFinal)executeSpeech(result[0].transcript)};recognition.onerror=e=>heard.textContent=e.error==="not-allowed"?"請允許瀏覽器使用麥克風後再試":"沒有聽清楚，請靠近麥克風再說一次";recognition.onend=()=>{listen.disabled=false;listen.classList.remove("listening");listen.querySelector("span").textContent="按一下說話"};listen.disabled=true;listen.classList.add("listening");listen.querySelector("span").textContent="正在聆聽…";heard.textContent="正在聽…例如說「前進 1 秒」";recognition.start()});
$("stop").addEventListener("click",()=>stopCar("已立即停止"));
